import { Language } from './types';

export const LANGUAGES: Language[] = [
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'mr', name: 'Marathi', nativeName: 'మరాఠీ' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά' },
  { code: 'he', name: 'Hebrew', nativeName: 'עבריత' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    AI_INTRUSION: 'AI INTRUSION',
    THE_WITNESSES: 'THE WITNESSES (CAST)',
    WHERE_TO_WITNESS: 'WHERE TO WITNESS',
    OVERVIEW: 'OVERVIEW',
    WATCHLISTED: 'WATCHLISTED',
    THE_VAULT: 'THE VAULT',
    SUMMONING_DETAILS: 'Summoning Details...',
    EXTRACTING_DATA: 'Extracting cinematic data...',
    GENERATIVE_VOICE: 'Generative Voice...',
    TRANSMITTING: 'Transmitting...',
    LISTEN_TO_BRIEF: 'Listen to Brief',
    NOT_AVAILABLE: 'NOT AVAILABLE FOR STREAMING',
    VAULT_TITLE: 'The Vault',
    VAULT_SUB: 'Your carefully selected collection of cinematic nightmares.',
    GATHERING_TROPHIES: 'Gathering your trophies...',
    WITNESSED_BY: 'Witnessed by',
    SPECIAL_SELECTION: 'Special Selection',
    TMDB_SCORE: 'TMDB Score',
    UA_RATING: 'U/A 16+',
    STORYBOARD_DATA: 'STORYBOARD DATA',
    WITNESS_LATER: 'Witness Later',
    PLAY_TRAILER: 'Play Trailer',
    AI_INTELLIGENCE: 'Gemini AI Intelligence',
    NEURAL_AUDIO: 'Neural Audio Generating...',
    STREAMING_BRIEF: 'Streaming Brief...',
    STREAM_AUDIO: 'Stream Audio Brief',
    ANALYSIS_COMPLETE: 'AI Analysis Complete',
    STARRING_CAST: 'Starring Cast',
    AVAILABLE_OTT: 'Available on OTT',
    NO_STREAMING: 'No streaming options found in your region.',
    TWISTED_TALES: 'Twisted Tales You May Like',
    LOADING_DARKNESS: 'LOADING DARKNESS...',
  },
  te: {
    AI_INTRUSION: 'AI విశ్లేషణ',
    THE_WITNESSES: 'నటీనటులు',
    WHERE_TO_WITNESS: 'ఎక్కడ చూడాలి',
    OVERVIEW: 'కథా సారాంశం',
    WATCHLISTED: 'జాబితాలో ఉంది',
    THE_VAULT: 'నా గ్యాలరీ',
    SUMMONING_DETAILS: 'వివరాలను సేకరిస్తోంది...',
    EXTRACTING_DATA: 'సినిమా సమాచారాన్ని విశ్లేషిస్తోంది...',
    GENERATIVE_VOICE: 'వాయిస్ జనరేట్ అవుతోంది...',
    TRANSMITTING: 'ప్రసారం అవుతోంది...',
    LISTEN_TO_BRIEF: 'క్లుప్తంగా వినండి',
    NOT_AVAILABLE: 'స్ట్రీమింగ్‌లో అందుబాటులో లేదు',
    VAULT_TITLE: 'నా గ్యాలరీ',
    VAULT_SUB: 'మీరు ఎంచుకున్న భయంకరమైన సినిమాల సమాహారం.',
    GATHERING_TROPHIES: 'మీ సేకరణను సిద్ధం చేస్తోంది...',
    WITNESSED_BY: 'వీక్షకులు',
    SPECIAL_SELECTION: 'ప్రత్యేక ఎంపిక',
    TMDB_SCORE: 'TMDB రేటింగ్',
    UA_RATING: 'U/A 16+',
    STORYBOARD_DATA: 'కథా విశ్లేషణ',
    WITNESS_LATER: 'తరువాత చూడండి',
    PLAY_TRAILER: 'ట్రైలర్ చూడండి',
    AI_INTELLIGENCE: 'Gemini AI తెలివితేటలు',
    NEURAL_AUDIO: 'వాయిస్ జనరేట్ అవుతోంది...',
    STREAMING_BRIEF: 'క్లుప్త వివరణ ప్రసారం...',
    STREAM_AUDIO: 'ఆడియో వివరణ వినండి',
    ANALYSIS_COMPLETE: 'AI విశ్లేషణ పూర్తయింది',
    STARRING_CAST: 'ముఖ్య నటీనటులు',
    AVAILABLE_OTT: 'OTT లో అందుబాటులో ఉంది',
    NO_STREAMING: 'మీ ప్రాంతంలో స్ట్రీమింగ్ అందుబాటులో లేదు.',
    TWISTED_TALES: 'మీకు నచ్చే భయానక చిత్రాలు',
    LOADING_DARKNESS: 'చీకటిని లోడ్ చేస్తోంది...',
  }
};

export const t = (key: string, langCode: string) => {
  return TRANSLATIONS[langCode]?.[key] || TRANSLATIONS['en']?.[key] || key;
};

// TMDB Genre IDs for DarkDoddle focus
export const GENRE_IDS = {
  HORROR: 27,
  CRIME: 80,
  THRILLER: 53,
  MYSTERY: 9648,
};

export const TMDB_IMAGE_BASE = 'https://image.tmdb.org/t/p/w500';
export const TMDB_BACKDROP_BASE = 'https://image.tmdb.org/t/p/original';
